language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t raxtone/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raxtone/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-089536118355"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "AKIARJWGEXZJZQWBO4NG"
  secret_access_key: "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"