language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t raxtone/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raxtone/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  # access_key_id: $AWS_ACCESS_KEY_ID
  # secret_access_key: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-089536118355"
  bucket_path: "docker-react"
  on:
    branch: master
  edge: true # opt in to travis v2