language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t raxtone/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true raxtone/docker-react npm run test